---
- name: Reset switch port to default
  hosts: switches
  gather_facts: false
  tasks:
    - name: Reset port
      ansible.builtin.include_role:
        name: agentless_net.l2.port
        tasks_from: reset_port
